---
# Ten playbook automatyzuje instalację Pi-hole na zdalnym serwerze.
# Używa oficjalnego skryptu instalacyjnego w trybie bezobsługowym.

- name: Automatic pihole installation
  hosts: pihole_hosts
  become: yes
  vars:
    pihole_install_script_url: "https://install.pi-hole.net"
    pihole_install_path: "/tmp/pihole-install.sh"

  tasks:
    - name: Pobieranie skryptu instalacyjnego Pi-hole
      ansible.builtin.get_url:
        url: "{{ pihole_install_script_url }}"
        dest: "{{ pihole_install_path }}"
        mode: '0755'
      # To zadanie pobiera skrypt instalacyjny z oficjalnej strony Pi-hole
      # i zapisuje go w tymczasowym katalogu.

    - name: Run installation - unattended mode
      ansible.builtin.shell:
        cmd: "{{ pihole_install_path }} --unattended"
      args:
        creates: /etc/pihole/setupVars.conf

    - name: Cleanup after installation
      ansible.builtin.file:
        path: "{{ pihole_install_path }}"
        state: absent

    - name: Configure static IP
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        line: "address 192.168.0.176"
        regexp: '^address'
        state: present

