---
- name: Test connectivity
  hosts: all

  tasks:
  - name: check remote vm's
    ping:

  - name: uptime check
    command: uptime
    register: uptime_output
  
  - name: display uptime
    debug:
      msg: "Uptime: {{ uptime_output.stdout}}"