---
- name: Instalacja serwera WWW Apache
  hosts: webservers
  become: yes

  tasks:
    - name: Update pack
      ansible.builtin.apt:
        update_cache: yes

    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: turn on service and put in started mode
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: port 80 opening / update rule on firewall
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == "Debian"
